ADJACENCY_MATRIX:
  - [0, 0, 0, 0]
  - [1, 0, 1, 1]
  - [0, 1, 0, 1]
  - [1, 1, 1, 0]

OFFSET: -0.2

DESIRED_DISTANCE_MATRIX:
  - [0, 0, 0, 0]
  - [2, 0, 1, 2.236]
  - [0, 1, 0, 2]
  - [1, 2.236, 2, 0]

NUM_OF_ROBOTS: 4
# TURTLEBOT3_MODEL: 'waffle_pi' 这条涉及太多代码 要写在环境变量里

# pi/4 = 0.7854 
INIT_POSE:
  - [0, 0, -3.14]
  - [-2, -0.2, -3.14]
  - [-3, -3.5, -3.14]
  - [-1, -2, -3.14]

V_MAX: 0.6
CONTROL_MODE: 'rigid'
LPF_RATIO: 0.95

K: 5.0
ALPHA: 2.0
BETA: 0.0
 
TANH_BETA: 0.43 # 用tanh代替sign的beta参数，和BETA不能同时开
TANH_K: 10

