ADJACENCY_MATRIX:
  - [0, 0, 0, 0]
  - [1, 0, 1, 1]
  - [0, 1, 0, 1]
  - [1, 1, 1, 0]

OFFSET: -0.3

DESIRED_DISTANCE_MATRIX:
  - [0, 0, 0, 0]
  - [2, 0, 1, 2.236]
  - [0, 1, 0, 2]
  - [1, 2.236, 2, 0]

NUM_OF_ROBOTS: 4
# TURTLEBOT3_MODEL: 'waffle_pi' 这条涉及太多代码 要写在环境变量里

# pi/4 = 0.7854 
INIT_POSE:
  - [0, 0, 0]
  - [-3, 0, 0]
  - [-3, -3, -0.523]
  - [-3, 3, 0.523]


